# Generated by Django 4.2.6 on 2023-10-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('domain', models.CharField(max_length=150, null=True)),
                ('year_founded', models.IntegerField(max_length=4, null=True)),
                ('industry', models.CharField(max_length=150, null=True)),
                ('size_range', models.CharField(max_length=100, null=True)),
                ('locality', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('linkedin_url', models.CharField(max_length=100, null=True)),
                ('current_employee_estimate', models.IntegerField(max_length=20, null=True)),
                ('total_employee_estimate', models.IntegerField(max_length=20, null=True)),
            ],
        ),
    ]
